### ISSUE TITLE
Same Wallpaper on all Screens

### ISSUE THREAD

**Issue by mjot** [evertdespiegeleer/PrettyEarth#1]
Hello,

first of all thank you for this great app. It's really amazing to have these great photos on my screen so easily.

But I have a question or rather a feature request. Would it be possible to display the same wallpaper on all screens? I am currently using 2 external screens and PrettyEarth only changes the background image of my main screen.

That would be great, thank you very much.

**Comment by evertdespiegeleer** [comment]
Thanks! That's great to hear.

I have thought about this during development, but there are a few reasons I haven't implemented it:

- It's surprisingly difficult and hacky to reliably change the wallpaper on a Mac programatically. [Here](https://github.com/evertdespiegeleer/PrettyEarth/blob/master/setWallpaper.js)'s the code that does that. As you can see it doesn't actually happen reliably. The code doesn't (and can't) check if the wallpaper really changes, it just throws the command at the computer and assumes it works. I tested it a lot and it never failed so it seems to work, but to my knowledge there's no check/callback possible. I tried other ways than AppleScript to do to the switching but this turned out to be the best one, and it's still pretty ugly code. It seemed to always work this way so I just carefully left it there and never touched it again.
- I actually incorrectly assumed it changed the wallpaper on all the screens, but I should have checked that
- I only have 1 screen which makes testing pretty difficult

However, I've read your feature request a few times on multiple platforms, so I will look into it.
I'm trying not to deviate from the AppleScript-solution, but I do think it can be done with AppleScript.

Thanks for the feedback!

**Comment by evertdespiegeleer** [comment]
@akramsaouri Fixed this. Thanks!

**Comment by mjot** [comment]
Could you create a new release? :)
